before_commands:
  - composer install --dev --prefer-source --no-interaction --dev

build:
  environment:
    php: 7.3.0
  tests:
    override:
      -
        command: bin/phpunit --coverage-clover=clover.xml
        coverage:
          file: clover.xml
          format: php-clover
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
          -
            command: phpcs-run
            use_website_config: true
filter:
  excluded_paths:
    - 'tests/*'
    - 'bin/*'
checks:
  php: true
coding_style:
  php: {  }